apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: skyline
  description: Enables basic auth smtp with ms graph
  annotations:
    backstage.io/linguist: https://github.com/kartverket/skyline
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: SKIP
  system: SKIP
