name: Publish TechDocs Site

on:
  push:
    branches: [ "main" ]
    paths:
     - "docs/**"
     - "mkdocs.yml"

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - id: 'techdocs-action'
        uses: kartverket/backstage-techdocs-action@v1
        with:
          entity_kind: component
          entity_name: skyline
          gcs_bucket_name: ${{vars.BACKSTAGE_TECHDOCS_GCS_BUCKET_NAME}}
          workload_identity_provider: ${{vars.BACKSTAGE_TECHDOCS_WIF}}
          service_account: ${{vars.BACKSTAGE_TECHDOCS_SERVICE_ACCOUNT}}
          project_id: ${{vars.BACKSTAGE_TECHDOCS_PROJECT_ID}}
